name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: doc2skill
            asset: doc2skill-linux
          - os: windows-latest
            binary: doc2skill.exe
            asset: doc2skill-windows.exe
          - os: macos-latest
            binary: doc2skill
            asset: doc2skill-macos
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - run: cp target/release/${{ matrix.binary }} target/release/${{ matrix.asset }}
      - name: Upload binary to release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload ${{ github.event.release.tag_name }} target/release/${{ matrix.asset }}

  publish:
    name: Publish to crates.io
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
